# add the following to _config.yml file
# Data Scientist
title: Parth Patel
theme: jeykll-theme-minimal

### Education
Electrical Enogineer, PhD.

### Work Experience
Data scientist @ Univristy of Texas at San Antonio
- 
-

###Projectw
**EEG Band Discovery**

etc...
