# Personal Information
title: Parth Patel
theme: jekyll-theme-minimal

# Education
education: 
  - degree: Electrical Engineer, PhD
    institution: University of Texas at San Antonio

# Work Experience
work_experience:
  - title: Data Scientist
    organization: University of Texas at San Antonio
    description: |
      Worked on various projects involving data analysis, machine learning, and AI models.

# Projects
projects:
  - title: EEG Band Discovery
    description: |
      Project focused on discovering EEG bands for brain activity analysis and categorization.

# Other Information
etc: |
  Additional info here if needed.
