# Personal Information
title: Parth Patel
theme: jekyll-theme-minimal

# Contact Information
email: parthpatel3343@gmail.com
location: Corpus Christi, TX, USA
linkedin: "https://linkedin.com/in/patelparth24/"
github: "https://github.com/patelandpatel"
leetcode: "https://leetcode.com/u/Parth71/"

# Education
education: 
  - degree: PhD, Computer Engineering
    institution: University of Texas at San Antonio
    dates: August 2023 - May 2025
  - degree: Master's, Computer Engineering
    institution: University of Texas at San Antonio
    dates: August 2021 - May 2023

# Work Experience
work_experience:
  - title: Research Scientist II
    organization: University of Texas - San Antonio
    location: San Antonio, TX, USA
    dates: August 2023 - Present
    description: |
      Developed a question-answering chatbot powered by Large Language Models (LLMs) to recommend books based on user reading interests and preferences.
      Leveraged OpenAI’s API, Prompt Engineering, and Langchain memory to enable personalized conversations and used Pinecone’s vector database to enhance recommendation accuracy.
      Modeled traffic scenarios as semantic scene graphs and analyzed for risk through safety metrics and GNNs.
      Proposed an explainable action recognition model to monitor driver distraction using a visual dictionary of human actions with Top-1 accuracy of 80.2% on a dataset of 10k+ videos.

# Projects
# [projects 1:  Human Action Recognition: Helping Autism](https://github.com/patelandpatel/AI-Data-driven-models-in-Human-Action-Recognition)
* Designed an AI/ML-based pilot program for recognizing human actions to assist autistic patients and their caregivers.
* Used Convolutional Neural Networks (CNN) to extract spatial features from video and Long Short-Term Memory (LSTM) to identify temporal relationships between frames, achieving 84% accuracy.
* Saved 120 hours per patient monthly in manual monitoring during the experimental phase.

  
# [Project 2: Snore Detection and Response Using a Fuzzy Inference System](https://github.com/patelandpatel/Snoring-Audio-Classifiction)
    description: |
      Led the creation of a snore detection system using CNN and Fuzzy Logic to analyze snoring sounds and trigger responses.
      Developed algorithms using Python, Matlab, and TensorFlow for audio signal processing, reducing snoring duration by 30%.
      Implemented haptic feedback notification for real-time intervention, improving users' sleep quality.
      

# Skills
skills:
  - Developer Tools: Microsoft Azure, Keras, scikit-learn, OpenCV, Google Cloud Platform, NumPy
  - Languages: Python, MySQL, MATLAB, Power BI


# Skills
skills:
  - Developer Tools: Microsoft Azure, Keras, scikit-learn, OpenCV, Google Cloud Platform, NumPy
  - Languages: Python, MySQL, MATLAB, Power BI
